/*
PROYECTO:		    EMPRESAS Y NEGOCIOS
AUTOR:			    HITSS BI - FERNANDA ZAMBRANO
OPERACIÓN: 		    SCRIPT ASOCIADO A NEGOCIOS FIJO
VERSIÓN:            V_1.0
FECHA:              02/09/2025
DESCRIPCIÓN:	    SCRIPT QUE PERMITE CONSULTAR TB_AUX_IMPORTACION_BASES
*/

SELECT 
    * 
FROM 
    proc_genericos.tb_aux_importacion_bases 
WHERE 
    id_base IN (13, 33, 34, 35, 36);

     --INCLUIR TODAS LAS COLUMNAS PASARLO A PY