consult_dim_agentes = """
         SELECT
        COD_AGENTE,COST_ID_AGENTE,CUSTCODE_AGENTE,NAME_AGENTE,ESTADO_AGENTE,
        CANAL as CANAL_COMERCIAL,SUBCANAL,CATEGORIA,REGION_COMERCIAL AS DIRECCION,GERENCIA,
        CIUDAD_AGENTE,DEPARTAMENTO,REGION_CONCESION,
        UNIDAD
        FROM DWH_DB.SEGMENTACION.inh_dim_agentes
        """

consulta_plan_negocios = """
         select * from DWH_DB.SEGMENTACION.INH_DIM_PLANES t
        """

consulta_cambio_plan = """
         select A.CO_ID
,('NEG_PLANES') as FLAG
,A.CUSTOMER_ID
,A.TELE_NUMB
,I.PRODUCTO AS TIPO_LINEA
,H.CD_SEGMENTO_CLIENTE AS CODIGO_SEGMENTO_CLIENTE
,D.CUSTCODE_AGENTE
,H.DS_SEGMENTO_CLIENTE AS SEGMENTACION
,H.DS_UNIDAD_NEGOCIO
,E.REGION_DESC AS REGION_GEOGRAFICA
,D.REGION_COMERCIAL
,D.GERENCIA
,D.CANAL
,D.COD_AGENTE
,TO_CHAR(cast(A.FE_ACTIVACION as DATE),'DD/MM/YYYY') FE_ACTIVACION
,G.COD_CICLO
,A.NO_DIA_CORTE_FACTURACION
,A.NO_MESES_ANTIGUEDAD
,M.DS_RANGO_ANTIGUEDAD
,I.COD_PLAN AS COD_PLAN_ORIGEN
,I.PLAN_DESC AS DS_PLAN_ORIGEN
,cast (I.VLR_CFM as numeric) AS CFM_PLAN_ORIGEN
,I.TIPO_PLAN AS TIPO_PLAN_ORIGEN
,N.DS_GAMA_PLAN AS DS_GAMA_PLAN_ORIGEN
,J.COD_PLAN AS COD_PLAN_DESTINO
,J.PLAN_DESC AS DS_PLAN_DESTINO
,pn.ban_pyme as PLAN_NEGOCIOS
,cast (J.VLR_CFM as numeric) AS CFM_PLAN_DESTINO
,J.TIPO_PLAN AS TIPO_PLAN_DESTINO
,O.DS_GAMA_PLAN AS DS_GAMA_PLAN_DESTINO
,cast (A.VL_CFM_NETO as numeric)
,TO_CHAR(cast(A.FE_CREACION as DATE),'DD/MM/YYYY') FE_CREACION
,A.NO_TICKLER
,TO_CHAR(cast(A.FE_CAMBIO as DATE),'DD/MM/YYYY') FE_CAMBIO
,L.DS_TIPO_GRADE
,P.CD_USUARIO_RED AS CD_USUARIO_RED_USUARIO_CRECION
,P.DS_NOMBRE_USUARIO AS DS_NOMBRE_USUARIO_CREACION
,P.DS_UBICACION_USUARIO AS DS_UBICACION_USUARIO_CREACION
,P.DS_CANAL_USUARIO AS DS_CANAL_USUARIO_CREACION
,CASE WHEN A.NO_EJECUTADO=1 then 'Cerrado' else 'Abierto' END ESTADO_TICKLER
,TO_CHAR(cast(A.FE_CIERRE as DATE),'DD/MM/YYYY') FE_CIERRE
,Q.CD_USUARIO_RED AS CD_USUARIO_RED_USUARIO_CIERRE
,Q.DS_NOMBRE_USUARIO AS DS_NOMBRE_USUARIO_CIERRE
,Q.DS_UBICACION_USUARIO AS DS_UBICACION_USUARIO_CIERRE
,Q.DS_CANAL_USUARIO AS DS_CANAL_USUARIO_CIERRE
,A.DS_TICKLER
,A.DS_NOMBRE_CLIENTE
,F.TIPO_IDENTIFICADOR_DESC
,A.DS_IDENTIFICACION
,T.IDENTIFICACION
,T.IDENTIFICACION_MTR
,A.DS_TELEFONO_1
,A.DS_TELEFONO_2
,A.IMEI
,A.IMSI
,cast (A.VL_CFM_NETO_CONTABLE_VOZ as numeric)
,cast (A.VL_CFM_NETO_CONTABLE_DATOS as numeric)
FROM DWH_DB.CLIENTES.TBL_FACT_CLIEN_CAMBIOS_PLAN_EJECUTADOS A
LEFT JOIN (SELECT CUSTCODE_AGENTE,REGION_COMERCIAL,GERENCIA,CANAL,COD_AGENTE FROM DWH_DB.SEGMENTACION.INH_DIM_AGENTES) D ON A.COD_AGENTE=D.COD_AGENTE
LEFT JOIN (SELECT REGION_DESC,COD_MERCADO FROM DWH_DB.SEGMENTACION.INH_DIM_REGIONES) E ON A.COD_MERCADO=E.COD_MERCADO
LEFT JOIN (SELECT TIPO_IDENTIFICADOR_DESC,TIPO_IDENTIFICACION FROM DWH_DB.SEGMENTACION.INH_DIM_TIPO_IDENTIFICADOR) F ON A.TIPO_IDENTIFICACION=F.TIPO_IDENTIFICACION
LEFT JOIN (SELECT COD_CICLO FROM DWH_DB.SEGMENTACION.INH_DIM_CICLOS) G ON A.COD_CICLO=G.COD_CICLO
LEFT JOIN (SELECT CD_SEGMENTO_CLIENTE, DS_SEGMENTO_CLIENTE, DS_UNIDAD_NEGOCIO,SK_SEGMENTO_CLIENTE FROM DWH_DB.CLIENTES.TBL_DIM_SEGMENTO_CLIENTE_T1) H ON A.SK_SEGMENTO_CLIENTE=H.SK_SEGMENTO_CLIENTE
LEFT JOIN (SELECT COD_PLAN,PLAN_DESC,VLR_CFM,TIPO_PLAN,PRODUCTO FROM DWH_DB.SEGMENTACION.INH_DIM_PLANES) I ON A.COD_PLAN_ORIGEN=I.COD_PLAN
LEFT JOIN (SELECT COD_PLAN,PLAN_DESC,VLR_CFM,TIPO_PLAN,PRODUCTO FROM DWH_DB.SEGMENTACION.INH_DIM_PLANES) J ON A.COD_PLAN_DESTINO=J.COD_PLAN
LEFT JOIN (SELECT DS_TIPO_GRADE,SK_TIPO_GRADE FROM DWH_DB.CLIENTES.TBL_DIM_TIPO_GRADE_T0) L ON A.SK_TIPO_GRADE=L.SK_TIPO_GRADE
LEFT JOIN (SELECT DS_RANGO_ANTIGUEDAD,SK_RANGO_ANTIGUEDAD FROM DWH_DB.CLIENTES.TBL_DIM_RANGO_ANTIGUEDAD_T1) M ON A.SK_RANGO_ANTIGUEDAD=M.SK_RANGO_ANTIGUEDAD
LEFT JOIN (SELECT DS_GAMA_PLAN,SK_GAMA_PLAN FROM DWH_DB.CLIENTES.TBL_DIM_GAMA_PLAN_T1) N ON A.SK_GAMA_PLAN_ORIGEN=N.SK_GAMA_PLAN
LEFT JOIN (SELECT DS_GAMA_PLAN,SK_GAMA_PLAN FROM DWH_DB.CLIENTES.TBL_DIM_GAMA_PLAN_T1) O ON A.SK_GAMA_PLAN_DESTINO=O.SK_GAMA_PLAN
LEFT JOIN (SELECT CD_USUARIO_RED,DS_NOMBRE_USUARIO,DS_UBICACION_USUARIO,DS_CANAL_USUARIO,SK_USUARIO_UBICACION FROM DWH_DB.CLIENTES.TBL_DIM_USUARIO_UBICACION_T2) P ON A.SK_USUARIO_CREACION=P.SK_USUARIO_UBICACION
LEFT JOIN (SELECT CD_USUARIO_RED,DS_NOMBRE_USUARIO,DS_UBICACION_USUARIO,DS_CANAL_USUARIO,SK_USUARIO_UBICACION FROM DWH_DB.CLIENTES.TBL_DIM_USUARIO_UBICACION_T2) Q ON A.SK_USUARIO_CIERRE=Q.SK_USUARIO_UBICACION
LEFT JOIN (SELECT CO_ID, IDENTIFICACION, IDENTIFICACION_MTR FROM SEGMENTACION.INH_SEG_BSCS_CLIENTES ) T ON A.CO_ID =T.CO_ID
LEFT JOIN (select BAN_PYME, COD_PLAN from DWH_DB.SEGMENTACION.INH_DIM_PLANES) PN on J.COD_PLAN = PN.cod_plan
WHERE cast(A.FE_CREACION as DATE) >= '2024-04-15'
and pn.ban_pyme = 'S'
        """

consulta_ventas = """
         SELECT
            ('NEGOCIOS') AS Segmento,
            R5.segmento AS FLAG,
            M.CLASECAUSALINIC,
            M.CO_ID,
            M.TELE_NUMB,
            M.PLAN,
            M.PAQUETE,
            M.TIPO,
            M.AGENT_CODE,
            translate(M.RAZON_INICIAL, 'áéíóú', 'aeiou') AS RAZON_INICIAL,
            translate(M.RAZON_FINAL, 'áéíóú', 'aeiou') AS RAZON_FINAL,
            M.FECHA_ULTEST,
            M.ACTIVACION,
            M.SSN,
            M.TMCYSPC,
            M.CIUDAD,
            CAST(M.CFM AS INTEGER),
            M.AGENT_NAME,
            M.DOCUMENTO,
            SUBSTRING(ciclo, POSITION(' - ' IN ciclo) + 2, 3) AS ciclo,
            M.identificacion_venderdor,
            M.CUSTCODE
        FROM 
            DWH.BSCS_ACTIVACIONES M
        JOIN 
            DWH_DB.VENTAS.TBL_VENT_SEG_INF_CONFIDENCIALES R5 ON M.SSN = R5.identificacion
        WHERE 
            (M.RAZON_INICIAL LIKE '%32%' OR 
             M.RAZON_INICIAL LIKE '%57%' OR 
             M.RAZON_INICIAL LIKE '%267%' OR 
             M.RAZON_INICIAL LIKE '%345%' OR 
             M.RAZON_INICIAL LIKE '%362%' OR 
             M.RAZON_INICIAL LIKE '%118%' OR 
             M.RAZON_INICIAL LIKE '%285%' OR 
             M.RAZON_INICIAL LIKE '%500%' OR 
             M.RAZON_INICIAL LIKE '%202%')
        
        UNION

        SELECT
            ('NEGOCIOS') AS Segmento,
            R5.segmento AS FLAG,
            M.CLASECAUSALINIC,
            M.CO_ID,
            M.TELE_NUMB,
            M.PLAN,
            M.PAQUETE,
            M.TIPO,
            M.AGENT_CODE,
            translate(M.RAZON_INICIAL, 'áéíóú', 'aeiou') AS RAZON_INICIAL,
            translate(M.RAZON_FINAL, 'áéíóú', 'aeiou') AS RAZON_FINAL,
            M.FECHA_ULTEST,
            M.ACTIVACION,
            M.SSN,
            M.TMCYSPC,
            M.CIUDAD,
            CAST(M.CFM AS INTEGER),
            M.AGENT_NAME,
            M.DOCUMENTO,
            SUBSTRING(ciclo, POSITION(' - ' IN ciclo) + 2, 3) AS ciclo,
            M.identificacion_venderdor,
            M.CUSTCODE
        FROM 
            DWH.BSCS_ACTIVACIONES M
        JOIN 
            DWH_DB.VENTAS.TBL_VENT_SEG_INF_CONFIDENCIALES R5 ON M.SSN = R5.identificacion
        WHERE 
            (M.RAZON_INICIAL LIKE '%333%' OR 
             M.RAZON_INICIAL LIKE '%444%' OR 
             M.RAZON_INICIAL LIKE '%555%' OR 
             M.RAZON_INICIAL LIKE '%666%' OR 
             M.RAZON_INICIAL LIKE '%777%')
        """


consulta_base_seg = """
         SELECT 
         x.identificacion  as CUST_ID,
        ('') as Cod_plan,
        x.segmento as Flag,
        ('') as Usuario
        FROM DWH_DB.VENTAS.TBL_VENT_SEG_INF_CONFIDENCIALES x
        WHERE CB_ESACTUAL='1' 
        """

consulta_cod_ciudad = """
          SELECT x.* FROM clientes.tbl_dim_distribuidor_bscs_t1 x
          where x.tipo_distribuidor in ('D','T','MAY','C')

        
        """