'''
PROYECTO:			 EMPRESAS Y NEGOCIOS
FRENTE DE TRABAJO:	 NEGOCIOS FIJO
NOMBRE FRENTE:		 NEGOCIOS FIJO DDL.
AUTOR:			     HITSS BI - JORGE MOSQUERA
OPERACION: 			 SCRIPT ROLLBACK PARA AJUSTAR CAMPOS EN LAS TABLAS DEL PROCESO NEGOCIOS FIJO
VERSION:			 V_1.0
FECHA:               17/07/2025
DESCRIPCION:	     SE CREA SCRIPT CON LOS ROLLBACK REQUERIDOS PARA EL PROCESO NEGOCIOS FIJO
'''

-- ROOLBACK tabla tb_base_planta_comercial campo estado 
ALTER TABLE proc_genericos.tb_base_planta_comercial
ALTER COLUMN estado VARCHAR(20);
